Reject differently sized symbols in the raptorcast receive path
Before this commit, it was possible to cause a crash (panic) in the
raptorcast receive path by sending a raptorcast node differently sized
encoded symbols that appear to be part of the same encoded message.

That is, without the checks that this commit adds in managed_decoder.rs
and udp.rs, the included different_symbol_sizes.rs test crashes the
RaptorCast instance it creates with the following panic, which is caused
by an internal symbol size mismatch:

    thread 'tokio-runtime-worker' panicked at monad-raptor/src/r10/nonsystematic/decoder/managed_decoder.rs:60:9:
    assertion `left == right` failed
      left: 1228
     right: 1248
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    error: test failed, to rerun pass `-p monad-raptorcast --test different_symbol_sizes`

With the checks included, the test case no longer crashes, and instead
logs a number of these messages:

    2024-09-17T19:40:10.057963Z  WARN monad_raptorcast::udp: ManagedDecoder::received_encoded_symbol returned error err=Custom { kind: InvalidData, error: "ManagedDecoder with symbol_len = 1228 given symbol of length 1248" } key=MessageCacheKey { unix_ts_ms: 0, author: 031b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f, app_message_hash: [177, 252, 60, 59, 244, 115, 89, 107, 200, 172, 31, 92, 134, 247, 124, 47, 192, 224, 24, 106], app_message_len: 100000 }