Make the monad-dataplane node example work again
Commit de9f6799bc74 ("Support interoperation of different MONAD_GSO_SIZE
values") broke the monad-dataplane node example by making the
transmission of a BroadcastMsg use a stride value that is the same size
as the entire message being transmitted, but the entire message is 96342
bytes long, which is larger than the maximum UDP packet size of ~64 KiB,
and which causes the following panic in the dataplane code:

    sending 10 pkts, 963420 bytes

    START: Instant { tv_sec: 166390, tv_nsec: 53574938 }
    thread '<unnamed>' panicked at monad-dataplane/src/network.rs:372:37:
    attempt to divide by zero
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Before that change, we would use the default monad-dataplane stride
size here, so this commit changes the example to use the newly added
DEFAULT_SEGMENT_SIZE as the message stride.  With this change, we get:

    sending 10 pkts, 963420 bytes

    START: Instant { tv_sec: 177585, tv_nsec: 527539108 }
    END: Instant { tv_sec: 177585, tv_nsec: 529013025 }

    RXer: cnt=20, bytes=963420
    run complete